// ============================================================
// FILE: rules/entries.ts — what a write actually produces.
//
// Every one of these was a `useCallback` inside `RecoveryDataProvider`, which
// meant the answer to "what happens when somebody saves an empty capture?"
// required React and a mocked AsyncStorage to ask. P1's promise — that the
// capture path never fails and never scolds — lived in a closure.
//
// Now they are data in, data out. The provider still owns state and
// persistence; these own the DECISION about what gets written.
//
// ─────────────────────────────────────────────────────────────────────────────
// `null` MEANS NO-OP, AND THAT IS THE POINT
//
// Several of these return `TimelineEntry | null`. The null is not an error
// channel — there is no error channel here, by design (P1) — it is the "nothing
// to save is not a failure" contract made into a type. A caller that gets null
// does nothing and says nothing, which is exactly what pressing save on an
// empty field should do.
//
// `now` and `id` are ARGUMENTS. A function that reads the clock or generates
// its own id cannot be asserted against, and the ids are the only thing here
// that is not deterministic.
// ============================================================

import type {
  Appointment, Milestone, PhotoEntry, QuickAnswer, CheckIn,
  TimelineEntry, WeeklyReflection,
} from "../types/recovery.ts";
import { detectTags } from "../data/captureTags.ts";

/** P1: one line, one save, no required fields, tags applied silently. */
export function captureEntry(
  journeyId: string, text: string, now: string, id: string, viaVoice?: boolean,
): TimelineEntry | null {
  const trimmed = text.trim();
  if (!trimmed) return null;
  return {
    id,
    journeyId,
    type: "capture",
    date: now,
    // The entry's title is the text AS WRITTEN. No truncation, no "Capture 3",
    // no generated summary — the timeline shows people their own words back.
    title: trimmed,
    isAutoGenerated: false,
    data: { text: trimmed, viaVoice, autoTags: detectTags(trimmed) },
  };
}

const QUICK_LABEL: Record<QuickAnswer, string> = {
  better: "Better",
  same: "Same",
  worse: "Worse",
};

/**
 * P3: `quick` alone is a COMPLETE check-in. The detail layer is optional and
 * cannot be required, which is why `detail` is optional here too — if this
 * signature ever demands more, the fast path has stopped being one.
 */
export function checkInEntry(
  journeyId: string, quick: QuickAnswer, detail: Omit<CheckIn, "quick"> | undefined,
  now: string, id: string,
): TimelineEntry {
  return {
    id,
    journeyId,
    type: "checkin",
    date: now,
    title: QUICK_LABEL[quick],
    isAutoGenerated: false,
    data: { quick, ...detail },
  };
}

/** §4.5. Either field alone is enough; both empty is a no-op. */
export function journalEntry(
  journeyId: string, title: string, detail: string, now: string, id: string,
): TimelineEntry | null {
  if (!title.trim() && !detail.trim()) return null;
  return {
    id,
    journeyId,
    type: "journal",
    date: now,
    title: title.trim() || "Journal entry",
    detail: detail.trim(),
    isAutoGenerated: false,
  };
}

/**
 * §4.11 / P10. Produces BOTH the photo record and its timeline entry, because
 * a photo that reaches one and not the other is the defect this port already
 * shipped once: filed as journal text, `photos` left empty, and PhotoCompare
 * with nothing to compare.
 *
 * The caption is optional, so the entry's title falls back to a neutral word
 * rather than to the uri. A file path on the timeline would be the app showing
 * its plumbing to somebody who has just photographed a surgical wound.
 */
export function photoEntry(
  journeyId: string, uri: string, caption: string, now: string, id: string, entryId: string,
): { photo: PhotoEntry; entry: TimelineEntry } | null {
  if (!uri.trim()) return null;
  const photo: PhotoEntry = {
    id,
    journeyId,
    uri,
    date: now,
    caption: caption.trim() || undefined,
  };
  return {
    photo,
    entry: {
      id: entryId,
      journeyId,
      type: "photo",
      date: now,
      title: photo.caption ?? "Photo",
      isAutoGenerated: false,
      data: photo,
    },
  };
}

/**
 * §4.5's one-tap promote. ADDITIVE AND ONE-WAY: the milestone points back at
 * the journal entry, and the entry is untouched. Moving it would mean somebody
 * tapping "promote" loses what they wrote, which is a punishing outcome for a
 * button whose whole purpose is to celebrate.
 */
export function milestoneFromEntry(entry: TimelineEntry, id: string): Milestone {
  return {
    id,
    journeyId: entry.journeyId,
    // The milestone carries the ENTRY's date, not today's. It marks when the
    // thing happened, not when it was noticed.
    date: entry.date,
    title: entry.title,
    fromJournalEntryId: entry.id,
  };
}

/** §4.10. Appended, never deduplicated — a repeated question is still a question. */
export function withQuestion(
  appointments: Appointment[], appointmentId: string, question: string,
): Appointment[] {
  const trimmed = question.trim();
  if (!trimmed) return appointments;
  return appointments.map((a) =>
    a.id === appointmentId ? { ...a, questions: [...a.questions, trimmed] } : a,
  );
}

/** P7. An empty reply is a no-op; an existing reply is replaced, never appended. */
export function withReflectionReply(
  reflections: WeeklyReflection[], weekStart: string, reply: string,
): WeeklyReflection[] {
  const trimmed = reply.trim();
  if (!trimmed) return reflections;
  return reflections.map((r) => (r.weekStart === weekStart ? { ...r, reply: trimmed } : r));
}

/**
 * A stored value, or the fallback.
 *
 * A CORRUPT VALUE IS TREATED AS ABSENT. Losing one malformed entry beats
 * refusing to open the screen it belongs to — the same reasoning that gives the
 * capture path no failure branch. This is separated from AsyncStorage so the
 * corruption case can be asserted without a device.
 */
export function parseStored<T>(raw: string | null, fallback: T): T {
  if (raw === null) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}
