// ============================================================
// FILE: types/recovery.ts — the Recovery Companion domain, per spec §6.
//
// The RN app inherited AnklePath's domain: exercises, a plan, four trackers. It
// is a fine model for a rehab programme and it is not this product. Recovery
// Companion's subject is a JOURNEY with a timeline running through it, and the
// timeline is the heart (§4.3) — everything else either writes to it or reads
// from it.
//
// These are §6's models. Where this file departs from the spec text it says so
// and why; silent divergence between a spec and the types built from it is how
// a document stops describing a product.
//
// ─────────────────────────────────────────────────────────────────────────────
// TWO SHAPES THAT ARE LOAD-BEARING RATHER THAN INCIDENTAL
//
// 1. `CheckIn.quick` is the ONLY required field. P3: "one tap on Better / Same
//    / Worse logs a valid check-in". Everything else is optional because the
//    check-in has to be completable by somebody in pain, medicated or foggy.
//    If a field here ever stops being optional, the fast path has stopped
//    being a fast path.
//
// 2. `QuickCapture.text` is the only required field of a capture, and there is
//    no category on it. P1: "capture something in ≤10 seconds without making a
//    single categorization decision". `autoTags` is applied SILENTLY and is
//    editable later; it is a convenience the app adds, never a question the app
//    asks. A required tag would make this type a lie about the principle.
// ============================================================

export type RecoveryType = "injury" | "surgery" | "illness" | "chronic" | "rehabilitation";

export interface RecoveryJourney {
  id: string;
  type: RecoveryType;
  condition: string;
  bodyPart?: string;
  label: string;
  /** ISO date. The Day-N counter is derived from this and never stored. */
  startDate: string;
  goal?: string;
  isActive: boolean;
}

export type TimelineEntryType =
  | "capture"
  | "checkin"
  | "symptom"
  | "note"
  | "journal"
  | "medication"
  | "appointment"
  | "photo"
  | "milestone"
  | "education"
  | "reflection";

export interface TimelineEntry {
  id: string;
  journeyId: string;
  type: TimelineEntryType;
  /** ISO datetime. */
  date: string;
  title: string;
  detail?: string;
  data?: TimelineEntryData;
  /**
   * Auto-generated entries mix with manual ones on one timeline (§4.3). The
   * flag exists so the UI can be honest about provenance, NOT so it can rank
   * them — a milestone the app noticed is worth as much as one the user wrote.
   */
  isAutoGenerated: boolean;
}

export type TimelineEntryData =
  | QuickCapture
  | CheckIn
  | MedicationEvent
  | Appointment
  | PhotoEntry
  | Milestone
  | WeeklyReflection;

/**
 * DEPARTS FROM §6, which types this as
 * `'pain' | 'sleep' | 'mood' | 'medication' | 'mobility'`.
 *
 * The design system's category families are pain | sleep | energy | mood |
 * meds, and two of the five names disagree — `mobility` has no family at all.
 * That matters because a tag has to RENDER: N4 forbids meaning by colour alone,
 * so every family carries an icon and a label beside its colours and
 * `restricted.mjs` fails the build if one does not. A `mobility` tag could only
 * be drawn as a colourless chip, or by inventing a sixth family for one word in
 * one spec sentence.
 *
 * The web prototype already resolved it this way. Two consumers of one token
 * source disagreeing about what a tag IS would be worse than either answer.
 * Recorded in DESIGN_CRITERIA §11.
 */
export type AutoTag = "pain" | "sleep" | "energy" | "mood" | "meds";

export interface QuickCapture {
  text: string;
  viaVoice?: boolean;
  /** Applied silently, editable later, never blocking the save (P1). */
  autoTags?: AutoTag[];
}

export type QuickAnswer = "better" | "same" | "worse";
export type ThreeLevel = 1 | 2 | 3;

export interface CheckIn {
  /** The fast path. The ONLY required field — see the header note. */
  quick: QuickAnswer;
  mood?: ThreeLevel;
  /** 0–10. */
  pain?: number;
  energy?: ThreeLevel;
  sleep?: ThreeLevel;
  mobility?: ThreeLevel;
  medicationTaken?: boolean;
  note?: string;
}

export interface CorridorPhase {
  fromDay: number;
  toDay: number;
  /** "Weight-bearing usually returns" — a common experience, never a target. */
  label: string;
  typicalPainRange?: [number, number];
  /**
   * Attribution is a REQUIRED field, not an optional one, and that is a
   * compliance decision rather than a stylistic one. P5 and §10 both require
   * corridor content to be evidence-based and cited; a phase with no source
   * cannot be reviewed, and unreviewable clinical-adjacent copy is the thing
   * this app is not allowed to ship.
   */
  sourceNote: string;
}

export interface RecoveryCorridor {
  condition: string;
  phases: CorridorPhase[];
  /**
   * Placeholder content is MARKED IN THE DATA, so the flag travels with the
   * content instead of living in a comment somebody has to remember to read.
   * The UI renders it. See data/recoveryCorridors.ts.
   */
  needsClinicalReview: boolean;
}

export interface Medication {
  id: string;
  journeyId: string;
  name: string;
  dosage: string;
  /** Times of day, e.g. ["08:00", "20:00"]. */
  schedule: string[];
  startDate: string;
  endDate?: string;
  reminders: boolean;
}

export interface MedicationEvent {
  medicationId: string;
  status: "taken" | "skipped";
  time: string;
}

export interface Appointment {
  id: string;
  journeyId: string;
  date: string;
  clinician?: string;
  location?: string;
  /** "Questions for my doctor" — addable any time, surfaced before the visit. */
  questions: string[];
  notesAfter?: string;
  followUpDate?: string;
}

export interface PhotoEntry {
  id: string;
  journeyId: string;
  /** A local URI. Never uploaded in Phase 1 — "stays on your device" (P10). */
  uri: string;
  date: string;
  caption?: string;
  bodyArea?: string;
}

export interface Milestone {
  id: string;
  journeyId: string;
  date: string;
  title: string;
  emoji?: string;
  fromJournalEntryId?: string;
  shareCardGenerated?: boolean;
}

export interface WeeklyReflection {
  weekStart: string;
  comparison: { metric: string; direction: "up" | "down" | "flat"; text: string }[];
  noticedDetail: string;
  encouragement: string;
  /**
   * NOT in §6. Added because P7's reward is being NOTICED, and a reflection the
   * user replied to is a different thing from one they scrolled past. The web
   * prototype persists exactly this and its behaviour test is what proves it.
   */
  reply?: string;
}

export type Trend = "improving" | "worsening" | "steady";

export interface Insight {
  id: string;
  journeyId: string;
  text: string;
  /**
   * §6 writes this as 'up' | 'down' | 'flat'. It is `Trend` here instead, and
   * the reason is recorded in DESIGN_CRITERIA §11: a raw direction has no
   * valence, so "pain up" and "sleep up" render identically while meaning
   * opposite things. The vocabulary is improving / worsening / steady on
   * screen, on paper and in the report — the icon carries direction, the word
   * carries valence.
   */
  trend: Trend;
  kind: "pain" | "sleep" | "mobility" | "adherence" | "correlation";
  isPremium?: boolean;
}

export interface DoctorReportConfig {
  journeyId: string;
  from: string;
  to: string;
  include: TimelineEntryType[];
}

// ── Derived, never stored ───────────────────────────────────────────────────

/**
 * Day N, inclusive of the start date — the first day of a recovery is Day 1,
 * not Day 0. Derived on read so it cannot drift from the start date, which is
 * the only fact actually recorded.
 */
export function dayNumber(startDate: string, now: number = Date.now()): number {
  const start = new Date(startDate).getTime();
  if (Number.isNaN(start)) return 1;
  const days = Math.floor((now - start) / 86_400_000);
  return Math.max(1, days + 1);
}
