// ============================================================
// THE PURE-RULE SUITE.
//
// These are the product's decisions, tested without a renderer. Until the
// `rules/` extraction, not one of them could be reached by anything except a
// running app, because every file that held them imported `react-native` on
// line one. The monetisation boundary, the report's refusal to guess, and the
// treatment of a gap were all unreachable by construction.
//
// RUN: node --test --experimental-strip-types tests/
// No jest, no babel, no transform step — Node 22 strips the types itself. That
// matters more than it sounds: a test suite that needs its own build is a test
// suite that stops running the first time the build breaks, and this repo has
// enough evidence about checks that quietly stop working.
//
// WHAT IS ASSERTED HERE, and it is not coverage for its own sake: every case
// below is a sentence from the spec or from §11, and several are cases that
// have ALREADY been shipped wrong somewhere in this repository.
// ============================================================

import { strict as assert } from "node:assert";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** Plain string paths: `new URL()` is a DOM type here and does not satisfy fs's PathLike. */
const RULES_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "rules");
import { describe, it } from "node:test";

import { compareStateOf, accessOf, journalStateOf } from "../src/rules/access.ts";
import { isReturn, ABSENCE_DAYS } from "../src/rules/absence.ts";
import { deriveReport, painScoresOf, MIN_FOR_TREND } from "../src/rules/report.ts";
import { withRestRows, restLabel } from "../src/rules/timeline.ts";
import { painTrend } from "../src/rules/trend.ts";
import { detectTags } from "../src/data/captureTags.ts";
import { corridorFor, phaseForDay, CORRIDORS } from "../src/data/recoveryCorridors.ts";
import { dayNumber } from "../src/types/recovery.ts";
import type { TimelineEntry } from "../src/types/recovery.ts";

const DAY = 86_400_000;

/** A check-in on a given ISO date, optionally with a pain score. */
function checkIn(date: string, pain?: number): TimelineEntry {
  return {
    id: date + (pain ?? "x"),
    journeyId: "j",
    type: "checkin",
    date,
    title: "Same",
    isAutoGenerated: false,
    data: pain === undefined ? { quick: "same" } : { quick: "same", pain },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
describe("P9 — where the gates are, and where they are not", () => {
  it("a non-subscriber sees the gate, not a shopping list", () => {
    assert.equal(compareStateOf(0, false), "locked");
    assert.equal(compareStateOf(1, false), "locked");
    assert.equal(compareStateOf(9, false), "locked");
  });

  it("A SUBSCRIBER WITH ONE PHOTO IS NEVER UPSOLD", () => {
    // The case the whole three-state design exists for. Without `insufficient`
    // somebody who has already paid is shown an upgrade prompt for the thing
    // they bought — and the order of the checks in compareStateOf is what
    // prevents the mirror-image failure, where a non-subscriber is told to come
    // back with more photos and THEN gated on arrival.
    assert.equal(compareStateOf(1, true), "insufficient");
    assert.equal(compareStateOf(0, true), "insufficient");
  });

  it("two photos and premium is the ready state", () => {
    assert.equal(compareStateOf(2, true), "ready");
  });

  it("a free article is free regardless of entitlement", () => {
    // "Everything answering what-is-normal is free forever" — the half of §9
    // that matters at 2am. There is deliberately no fourth state for a
    // subscriber reading a free article.
    assert.equal(accessOf("free", false), "free");
    assert.equal(accessOf("free", true), "free");
  });

  it("only deep dives gate", () => {
    assert.equal(accessOf("deepDive", false), "deepDiveLocked");
    assert.equal(accessOf("deepDive", true), "deepDiveOpen");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("N6 — the report has no entitlement input at all", () => {
  it("deriveReport's signature cannot express a gate", () => {
    // Not a behavioural assertion but a structural one, and it is the strongest
    // form N6 can take in a pure function: there is no premium parameter, so
    // there is no way to write the gate even by mistake. An audit found the
    // report gated or sold in ten places; two had been photographed into
    // passing baselines.
    assert.equal(deriveReport.length, 2);
  });

  it("depth degrades on data alone", () => {
    assert.equal(deriveReport([], undefined).depth, "empty");
    assert.equal(deriveReport([checkIn("2026-01-01T09:00:00Z", 5)], undefined).depth, "sparse");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("§4.7 — the report refuses to guess", () => {
  const anchor = Date.parse("2026-02-01T00:00:00Z");
  const before = [
    checkIn("2026-01-20T09:00:00Z", 7),
    checkIn("2026-01-22T09:00:00Z", 7),
    checkIn("2026-01-24T09:00:00Z", 8),
  ];
  const after = [
    checkIn("2026-02-05T09:00:00Z", 3),
    checkIn("2026-02-07T09:00:00Z", 3),
    checkIn("2026-02-09T09:00:00Z", 2),
  ];

  it("empty is reachable on day one and is not a failure", () => {
    const m = deriveReport([], undefined);
    assert.equal(m.depth, "empty");
    assert.equal(m.change, "noAnchor");
    assert.equal(m.changeText, "");
  });

  it("sparse degrades rather than drawing a trend from two points", () => {
    const m = deriveReport([checkIn("2026-01-01T09:00:00Z", 5), checkIn("2026-01-02T09:00:00Z", 2)], undefined);
    assert.equal(m.depth, "sparse");
    // Two points that "look" like a dramatic improvement produce no claim.
    assert.equal(m.changeText, "");
  });

  it("MIN_FOR_TREND is the boundary, and it is inclusive", () => {
    const scores = Array.from({ length: MIN_FOR_TREND }, (_, i) => checkIn(`2026-01-0${i + 1}T09:00:00Z`, 5));
    assert.equal(deriveReport(scores.slice(0, MIN_FOR_TREND - 1), undefined).depth, "sparse");
    assert.equal(deriveReport(scores, undefined).depth, "first");
  });

  it("first: the data is fine, the anchor is missing", () => {
    const m = deriveReport([...before, ...after], undefined);
    assert.equal(m.depth, "first");
    assert.equal(m.change, "noAnchor");
  });

  it("insufficient: an anchor, but too little either side to be fair", () => {
    const m = deriveReport([checkIn("2026-01-20T09:00:00Z", 7), ...after], anchor);
    assert.equal(m.change, "insufficient");
    assert.equal(m.changeText, "");
  });

  it("STEADY IS A FINDING, not a failure to improve", () => {
    // The guilt-risk case. It must produce a claim rather than falling through
    // to silence, and the claim must be neutral.
    const flat = [
      checkIn("2026-01-20T09:00:00Z", 5), checkIn("2026-01-22T09:00:00Z", 5),
      checkIn("2026-02-05T09:00:00Z", 5), checkIn("2026-02-07T09:00:00Z", 5),
    ];
    const m = deriveReport(flat, anchor);
    assert.equal(m.change, "noChange");
    assert.equal(m.trend, "steady");
    assert.match(m.changeText, /steady/i);
  });

  it("FALLING PAIN IS IMPROVING — the one place a smaller number is good news", () => {
    const m = deriveReport([...before, ...after], anchor);
    assert.equal(m.change, "changes");
    assert.equal(m.trend, "improving");
    assert.match(m.changeText, /lower/);
  });

  it("rising pain is worsening, and the word carries the valence", () => {
    const m = deriveReport([...after.map((e) => checkIn(e.date, 8)), ...before.map((e) => checkIn(e.date, 2))], anchor);
    assert.equal(m.trend, "worsening");
  });

  it("the split is around the ANCHOR, not around now", () => {
    // If this used `Date.now()` the fixture would drift into one side and the
    // comparison would silently become a different claim.
    const m = deriveReport([...before, ...after], anchor);
    assert.equal(m.change, "changes");
    const shifted = deriveReport([...before, ...after], Date.parse("2026-03-01T00:00:00Z"));
    assert.equal(shifted.change, "insufficient");
  });

  it("pain scores come back newest first", () => {
    const scores = painScoresOf([...before, ...after]);
    assert.deepEqual(scores, [2, 3, 3, 8, 7, 7]);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P2 — a gap is rest, and rest is never counted against anybody", () => {
  it("A RUN OF EMPTY DAYS IS ONE ROW, NOT ONE ROW PER DAY", () => {
    // Seven "a quiet day" rows would be an accusation repeated seven times,
    // however gently each one is worded. This is the arithmetic no contrast
    // check or token contract could ever see.
    const rows = withRestRows([checkIn("2026-01-01T09:00:00Z"), checkIn("2026-01-09T09:00:00Z")]);
    const rest = rows.filter((r) => r.kind === "rest");
    assert.equal(rest.length, 1);
    assert.equal(rest[0].kind === "rest" && rest[0].days, 7);
  });

  it("consecutive days produce no rest row", () => {
    const rows = withRestRows([checkIn("2026-01-01T09:00:00Z"), checkIn("2026-01-02T09:00:00Z")]);
    assert.equal(rows.filter((r) => r.kind === "rest").length, 0);
  });

  it("several entries on ONE day produce no rest row", () => {
    // Measured between day keys, not timestamps. Otherwise two captures an hour
    // apart get a rest row claiming zero quiet days.
    const rows = withRestRows([checkIn("2026-01-01T09:00:00Z"), checkIn("2026-01-01T21:00:00Z")]);
    assert.equal(rows.filter((r) => r.kind === "rest").length, 0);
  });

  it("unsorted input still produces correct gaps", () => {
    const rows = withRestRows([checkIn("2026-01-01T09:00:00Z"), checkIn("2026-01-09T09:00:00Z"), checkIn("2026-01-05T09:00:00Z")]);
    const rest = rows.filter((r) => r.kind === "rest").map((r) => (r.kind === "rest" ? r.days : 0));
    assert.deepEqual(rest, [3, 3]);
  });

  it("the copy is descriptive and never evaluative", () => {
    assert.equal(restLabel(1), "A quiet day");
    assert.equal(restLabel(12), "12 quiet days");
    for (const n of [1, 3, 7, 30, 200]) {
      const label = restLabel(n);
      // No threshold at which this becomes a warning, and no debt vocabulary.
      assert.doesNotMatch(label, /miss|behind|catch|should|lapsed|broke/i);
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P2 — welcome back, with no count of what was missed", () => {
  const now = Date.parse("2026-03-01T12:00:00Z");

  it("a first-ever open is NOT a return", () => {
    // Greeting a brand new user with "good to see you again" is a small lie
    // told at the first moment they use the product.
    assert.equal(isReturn(null, now), false);
  });

  it("a weekend is not an absence", () => {
    assert.equal(isReturn(now - 2 * DAY, now), false);
  });

  it("the boundary is inclusive at ABSENCE_DAYS", () => {
    assert.equal(isReturn(now - ABSENCE_DAYS * DAY, now), true);
    assert.equal(isReturn(now - (ABSENCE_DAYS * DAY - 1), now), false);
  });

  it("A BACKWARDS CLOCK IS NOT A LONG ABSENCE", () => {
    // Timezone change or a manual clock set. Comparing a gap rather than a date
    // is what makes this fall out instead of needing a special case.
    assert.equal(isReturn(now + 30 * DAY, now), false);
  });

  it("the module exports no duration anywhere", () => {
    // The structural half of P2: a `daysAway` in scope is a number somebody
    // eventually renders. isReturn returns a boolean and nothing else.
    assert.equal(typeof isReturn(now - 12 * DAY, now), "boolean");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P4 — the sentence above the chart, including its refusal", () => {
  it("declines to claim a trend from too little", () => {
    const claim = painTrend([3], [7, 7]);
    assert.equal(claim.trend, "steady");
    assert.match(claim.text, /not enough/i);
  });

  it("the refusal does not blame the user for not logging", () => {
    const claim = painTrend([], []);
    assert.doesNotMatch(claim.text, /should|need to|must|try to|missed/i);
  });

  it("lower pain reads as improving", () => {
    assert.equal(painTrend([2, 3], [7, 8]).trend, "improving");
  });

  it("higher pain reads as worsening", () => {
    assert.equal(painTrend([7, 8], [2, 3]).trend, "worsening");
  });

  it("a difference under the meaningful delta is steady, not a micro-trend", () => {
    assert.equal(painTrend([5, 5], [5.2, 5.1]).trend, "steady");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P1 — silent tagging that never blocks a save", () => {
  it("the normal capture has no tags, and that is not a deficiency", () => {
    assert.deepEqual(detectTags("took the long way round the block today"), []);
  });

  it("matches whole words only", () => {
    // Substring matching was the first attempt and it tagged half of
    // everything: "restless" became `rest`, "medical" became `meds`.
    assert.deepEqual(detectTags("restless and medical"), []);
    assert.deepEqual(detectTags("could not rest"), ["sleep"]);
  });

  it("returns a stable order regardless of the order words appear", () => {
    // A tag row that reshuffled between renders would be noise pretending to
    // be information.
    assert.deepEqual(detectTags("dose then pain"), ["pain", "meds"]);
    assert.deepEqual(detectTags("pain then dose"), ["pain", "meds"]);
  });

  it("is total — no input produces a throw", () => {
    for (const input of ["", "   ", "!!!", "PAIN", "pain,", "pain."]) {
      assert.doesNotThrow(() => detectTags(input));
    }
    assert.deepEqual(detectTags("PAIN"), ["pain"]);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P5 / N5 — the corridor is a range and never a deadline", () => {
  it("every phase spans days rather than naming one", () => {
    for (const corridor of CORRIDORS) {
      for (const phase of corridor.phases) {
        assert.ok(phase.toDay > phase.fromDay, `${corridor.condition}: ${phase.label} is not a range`);
      }
    }
  });

  it("EVERY PHASE CARRIES A SOURCE — a compliance requirement, not a style", () => {
    for (const corridor of CORRIDORS) {
      for (const phase of corridor.phases) {
        assert.ok(phase.sourceNote.trim().length > 0, `${corridor.condition}: ${phase.label} has no source`);
      }
    }
  });

  it("every corridor is flagged for clinical review while it is placeholder", () => {
    for (const corridor of CORRIDORS) {
      assert.equal(corridor.needsClinicalReview, true, `${corridor.condition} is not flagged`);
    }
  });

  it("no phase label implies a deadline or a failure to meet one", () => {
    for (const corridor of CORRIDORS) {
      for (const phase of corridor.phases) {
        assert.doesNotMatch(phase.label, /should|must|target|deadline|by now|expected to|behind|on track/i);
      }
    }
  });

  it("PAST THE LAST PHASE THE CORRIDOR STOPS rather than pinning the final one", () => {
    // Clamping would leave somebody on day 400 looking at the final phase
    // indefinitely, which turns a range into an overdue notice.
    const corridor = corridorFor("Ankle ligament injury (sprain)");
    assert.ok(corridor);
    assert.equal(phaseForDay(corridor!, 400), undefined);
    assert.ok(phaseForDay(corridor!, 1));
  });

  it("an unknown condition simply has no corridor", () => {
    assert.equal(corridorFor("something we do not cover"), undefined);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("Day N", () => {
  it("the first day of a recovery is Day 1, not Day 0", () => {
    const start = "2026-01-01T00:00:00Z";
    assert.equal(dayNumber(start, Date.parse("2026-01-01T23:59:00Z")), 1);
    assert.equal(dayNumber(start, Date.parse("2026-01-02T00:00:00Z")), 2);
  });

  it("never goes below 1, even with a start date in the future", () => {
    assert.equal(dayNumber("2030-01-01T00:00:00Z", Date.parse("2026-01-01T00:00:00Z")), 1);
  });

  it("a malformed start date degrades to Day 1 rather than NaN", () => {
    assert.equal(dayNumber("not a date"), 1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("§4.5 — promotion is one-way and additive", () => {
  const entry: TimelineEntry = {
    id: "j1", journeyId: "j", type: "journal", date: "2026-01-01T09:00:00Z",
    title: "A week in", detail: "Slower than I expected.", isAutoGenerated: false,
  };

  it("no entry means composing", () => {
    assert.equal(journalStateOf(undefined, []), "composing");
  });

  it("an entry with no body means composing", () => {
    assert.equal(journalStateOf({ ...entry, detail: "   " }, []), "composing");
  });

  it("an entry with no milestone pointing at it is reading", () => {
    assert.equal(journalStateOf(entry, [{ fromJournalEntryId: "other" }]), "reading");
  });

  it("THE ENTRY SURVIVES PROMOTION — it is not consumed", () => {
    // Promotion adds a milestone; it does not move or delete what was written.
    // `promoted` therefore describes an entry that still exists.
    assert.equal(journalStateOf(entry, [{ fromJournalEntryId: "j1" }]), "promoted");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("the constraint that makes all of the above possible", () => {
  it("NOTHING IN rules/ IMPORTS REACT OR REACT NATIVE", () => {
    // The entire value of this suite rests on this one property. Every rule
    // here previously lived inside a component, and that is precisely why none
    // of them could be tested: the file imported `react-native` on line one.
    //
    // A rules module that quietly grows a `useState` is a rules module that has
    // stopped being testable and has taken these tests down with it — silently,
    // because the failure would look like an import error in a suite nobody
    // runs rather than like a broken rule.
    const offenders: string[] = [];
    for (const name of readdirSync(RULES_DIR)) {
      if (!name.endsWith(".ts")) continue;
      const src = readFileSync(join(RULES_DIR, name), "utf8");
      if (/from\s+["'](react|react-native)["']/.test(src)) offenders.push(name);
    }
    assert.deepEqual(offenders, [], `rules/ must stay pure; these import a renderer: ${offenders.join(", ")}`);
  });

  it("rules/ imports nothing from a screen or a component either", () => {
    // Same argument one level out. A rule that reaches into a screen has
    // inverted the dependency and will drag the renderer in behind it.
    const offenders: string[] = [];
    for (const name of readdirSync(RULES_DIR)) {
      if (!name.endsWith(".ts")) continue;
      const src = readFileSync(join(RULES_DIR, name), "utf8");
      if (/from\s+["'][^"']*(screens|components|state)\//.test(src)) offenders.push(name);
    }
    assert.deepEqual(offenders, []);
  });
});
