// ============================================================
// THE STORE AND ADAPTER SUITE.
//
// What a write produces, and which record an adapter resolves. Every function
// under test here was a `useCallback` inside `RecoveryDataProvider` or a
// closure inside a route adapter, which meant the answer to "what happens when
// somebody saves an empty capture?" needed React and a mocked AsyncStorage to
// ask — so nobody asked.
//
// The provider still owns state and persistence. These own the DECISION.
//
// THE PHOTO CASE IS WHY THIS SUITE EXISTS. This port already shipped a route
// that filed a photo as a journal entry with the file path as its body: a uri
// on the timeline, `photos` left empty, PhotoCompare with nothing to compare.
// It typechecked perfectly, and it was found by re-reading the adapter rather
// than by anything automatic. That class of bug is exactly what is asserted
// below.
// ============================================================

import { strict as assert } from "node:assert";
import { describe, it } from "node:test";

import {
  captureEntry, checkInEntry, journalEntry, milestoneFromEntry,
  parseStored, photoEntry, withQuestion, withReflectionReply,
} from "../src/rules/entries.ts";
import { comparePair, lastVisit, nextAppointment } from "../src/rules/select.ts";
import type { Appointment, PhotoEntry, TimelineEntry, WeeklyReflection } from "../src/types/recovery.ts";

const NOW = "2026-03-01T10:00:00.000Z";
const J = "journey-1";

const appointment = (id: string, date: string, questions: string[] = []): Appointment =>
  ({ id, journeyId: J, date, questions });

const photo = (id: string, date: string): PhotoEntry =>
  ({ id, journeyId: J, uri: `file://${id}`, date });

// ─────────────────────────────────────────────────────────────────────────────
describe("P1 — the capture path never fails and never scolds", () => {
  it("AN EMPTY SAVE IS A NO-OP, NOT A REFUSAL", () => {
    // `null` is not an error channel — there is no error channel here by
    // design. It is "nothing to save is not a failure" made into a type.
    assert.equal(captureEntry(J, "", NOW, "id"), null);
    assert.equal(captureEntry(J, "   \n  ", NOW, "id"), null);
  });

  it("the timeline shows people their own words back, untouched", () => {
    const long = "knee hurt after the stairs today and I am fed up about it, honestly";
    const entry = captureEntry(J, long, NOW, "id");
    // No truncation, no "Capture 3", no generated summary.
    assert.equal(entry?.title, long);
    assert.equal((entry?.data as { text: string }).text, long);
  });

  it("surrounding whitespace is trimmed but the text is not otherwise altered", () => {
    const entry = captureEntry(J, "  took the long way round  ", NOW, "id");
    assert.equal(entry?.title, "took the long way round");
  });

  it("tags are applied silently and never block the save", () => {
    const tagged = captureEntry(J, "knee pain after stairs", NOW, "id");
    assert.deepEqual((tagged?.data as { autoTags: string[] }).autoTags, ["pain", "energy"]);
    // And an untaggable capture still saves — the normal case.
    const plain = captureEntry(J, "went outside", NOW, "id");
    assert.ok(plain);
    assert.deepEqual((plain?.data as { autoTags: string[] }).autoTags, []);
  });

  it("a capture is never marked auto-generated", () => {
    assert.equal(captureEntry(J, "something", NOW, "id")?.isAutoGenerated, false);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P3 — one tap is a complete check-in", () => {
  it("saves with no detail at all", () => {
    const entry = checkInEntry(J, "better", undefined, NOW, "id");
    assert.equal(entry.type, "checkin");
    assert.deepEqual(entry.data, { quick: "better" });
  });

  it("NEVER RETURNS NULL — a check-in cannot be rejected", () => {
    // Contrast with capture and journal, which have an empty case. A fast path
    // that can decline has stopped being a fast path.
    for (const quick of ["better", "same", "worse"] as const) {
      assert.ok(checkInEntry(J, quick, undefined, NOW, "id"));
    }
  });

  it("the title is the word, so the timeline reads without opening anything", () => {
    assert.equal(checkInEntry(J, "worse", undefined, NOW, "id").title, "Worse");
  });

  it("optional detail is merged without displacing the required answer", () => {
    const entry = checkInEntry(J, "same", { pain: 4, sleep: 2 }, NOW, "id");
    assert.deepEqual(entry.data, { quick: "same", pain: 4, sleep: 2 });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("§4.5 — the journal", () => {
  it("either field alone is enough", () => {
    assert.ok(journalEntry(J, "A week in", "", NOW, "id"));
    assert.ok(journalEntry(J, "", "Slower than I expected.", NOW, "id"));
  });

  it("both empty is a no-op", () => {
    assert.equal(journalEntry(J, "  ", "\n", NOW, "id"), null);
  });

  it("an untitled entry gets a neutral name rather than a slice of the body", () => {
    assert.equal(journalEntry(J, "", "Some long body text here.", NOW, "id")?.title, "Journal entry");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("§4.11 / P10 — the photo lane", () => {
  it("PRODUCES BOTH RECORDS OR NEITHER", () => {
    // The exact defect this port shipped: the timeline entry existed and the
    // photo record did not, so PhotoCompare had nothing to compare.
    const made = photoEntry(J, "file://abc", "Day 3", NOW, "p1", "e1");
    assert.ok(made);
    assert.equal(made!.photo.uri, "file://abc");
    assert.equal(made!.entry.type, "photo");
    assert.equal(made!.entry.data, made!.photo);
  });

  it("NEVER PUTS A FILE PATH ON THE TIMELINE", () => {
    // The caption is optional, so an uncaptioned photo must fall back to a
    // neutral word — not to the uri. A file path on the timeline is the app
    // showing its plumbing to somebody who has photographed a surgical wound.
    const made = photoEntry(J, "file:///var/mobile/tmp/IMG_0042.HEIC", "", NOW, "p1", "e1");
    assert.equal(made!.entry.title, "Photo");
    assert.doesNotMatch(made!.entry.title, /file:|\/|\.HEIC/i);
  });

  it("uses the caption as the title when there is one", () => {
    assert.equal(photoEntry(J, "file://a", "Swelling looks lower", NOW, "p", "e")!.entry.title, "Swelling looks lower");
  });

  it("an absent caption is undefined rather than an empty string", () => {
    assert.equal(photoEntry(J, "file://a", "   ", NOW, "p", "e")!.photo.caption, undefined);
  });

  it("no uri is a no-op", () => {
    assert.equal(photoEntry(J, "", "caption", NOW, "p", "e"), null);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("§4.5 — promotion is additive and one-way", () => {
  const entry: TimelineEntry = {
    id: "j1", journeyId: J, type: "journal", date: "2026-01-05T09:00:00Z",
    title: "Walked to the end of the road", detail: "Further than last week.", isAutoGenerated: false,
  };

  it("the milestone points back at the entry", () => {
    assert.equal(milestoneFromEntry(entry, "m1").fromJournalEntryId, "j1");
  });

  it("THE MILESTONE CARRIES THE ENTRY'S DATE, not today's", () => {
    // It marks when the thing happened, not when somebody noticed it. A
    // milestone dated on the day of promotion would put "walked to the end of
    // the road" at the wrong point on the timeline forever.
    assert.equal(milestoneFromEntry(entry, "m1").date, entry.date);
  });

  it("the original entry is not mutated", () => {
    const snapshot = JSON.stringify(entry);
    milestoneFromEntry(entry, "m1");
    assert.equal(JSON.stringify(entry), snapshot);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("§4.10 — questions", () => {
  const list = [appointment("a1", "2026-04-01T10:00:00Z", ["When can I drive?"]), appointment("a2", "2026-01-01T10:00:00Z")];

  it("appends to the right appointment and leaves the others alone", () => {
    const next = withQuestion(list, "a1", "Is the swelling normal?");
    assert.deepEqual(next[0].questions, ["When can I drive?", "Is the swelling normal?"]);
    assert.equal(next[1], list[1]);
  });

  it("an empty question is a no-op AND returns the same array", () => {
    // Identity matters: the provider skips the write when nothing changed.
    assert.equal(withQuestion(list, "a1", "   "), list);
  });

  it("a repeated question is still a question", () => {
    // Not deduplicated on purpose. Somebody writing the same worry down twice
    // is telling you something, and silently dropping it would be the app
    // deciding it knows better.
    const next = withQuestion(list, "a1", "When can I drive?");
    assert.equal(next[0].questions.length, 2);
  });

  it("an unknown appointment id changes nothing", () => {
    assert.deepEqual(withQuestion(list, "nope", "x")[0].questions, ["When can I drive?"]);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("P7 — the weekly reply", () => {
  const list: WeeklyReflection[] = [
    { weekStart: "2026-02-01", comparison: [], noticedDetail: "d", encouragement: "e" },
  ];

  it("saves the reply", () => {
    assert.equal(withReflectionReply(list, "2026-02-01", " Good week. ")[0].reply, "Good week.");
  });

  it("REPLACES an existing reply rather than appending", () => {
    const once = withReflectionReply(list, "2026-02-01", "first");
    assert.equal(withReflectionReply(once, "2026-02-01", "second")[0].reply, "second");
  });

  it("an empty reply is a no-op and returns the same array", () => {
    assert.equal(withReflectionReply(list, "2026-02-01", ""), list);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("storage — a corrupt value is treated as absent", () => {
  it("returns the fallback for missing and for malformed", () => {
    assert.deepEqual(parseStored(null, []), []);
    assert.deepEqual(parseStored("{not json", { a: 1 }), { a: 1 });
    assert.deepEqual(parseStored("", "fallback"), "fallback");
  });

  it("LOSING ONE ENTRY BEATS REFUSING TO OPEN THE SCREEN", () => {
    // The same reasoning that gives the capture path no failure branch. This
    // must never throw, whatever is in storage.
    for (const junk of ["undefined", "[1,2", " ", "NaN", '{"a":'])
      assert.doesNotThrow(() => parseStored(junk, null));
  });

  it("parses a good value", () => {
    assert.deepEqual(parseStored('{"a":1}', null), { a: 1 });
  });

  it("A VALUE THAT PARSES BUT IS THE WRONG SHAPE IS ALSO ABSENT", () => {
    // The half of the input space the first version was not looking at. It
    // guarded the PARSE, so "corrupt" meant "throws" — and `"null"`, `"5"` and
    // `"{}"` are all valid JSON. Each one hydrated `timeline` as a non-array,
    // and the next line to touch it was `[entry, ...timeline]`.
    //
    // `harness/slice.spec.ts` measured what that produces: `TypeError: timeline
    // is not iterable`, an empty body, a total crash on launch. On a device
    // that is a white screen on a health app holding somebody's recovery, with
    // no way out but clearing app data.
    for (const wrong of ["null", "5", "{}", '"a string"', "true"]) {
      assert.deepEqual(parseStored(wrong, [] as unknown[]), [], `array fallback vs ${wrong}`);
    }
    // And the other direction: an array where a record was expected.
    assert.deepEqual(parseStored("[1,2,3]", { a: 1 }), { a: 1 });
    assert.deepEqual(parseStored("null", { a: 1 }), { a: 1 });
    // Primitives keep their own type too — `seeded` is a boolean.
    assert.equal(parseStored('"true"', false), false);
    assert.equal(parseStored("null", false), false);
    assert.equal(parseStored("true", false), true);
  });

  it("a null fallback still accepts a value, because the caller asked for one", () => {
    // `lastOpened` is `number | null`. Rejecting a number there would break the
    // welcome-back decision on every launch after the first — a guard that
    // "fixes" corruption by discarding good data is not a fix.
    assert.equal(parseStored("1772000000000", null as number | null), 1772000000000);
    assert.equal(parseStored("null", null as number | null), null);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe("adapters — which record a screen is handed", () => {
  const now = Date.parse("2026-03-01T00:00:00Z");

  it("the soonest UPCOMING appointment wins", () => {
    const list = [
      appointment("far", "2026-06-01T10:00:00Z"),
      appointment("soon", "2026-03-03T10:00:00Z"),
      appointment("past", "2026-01-01T10:00:00Z"),
    ];
    assert.equal(nextAppointment(list, now)?.id, "soon");
  });

  it("FALLS BACK TO THE MOST RECENT PAST ONE rather than to nothing", () => {
    // Otherwise somebody whose appointments are all behind them gets an empty
    // Profile row and a dead nudge.
    const list = [appointment("old", "2025-01-01T10:00:00Z"), appointment("recent", "2026-02-01T10:00:00Z")];
    assert.equal(nextAppointment(list, now)?.id, "recent");
  });

  it("undefined only when there are none at all", () => {
    assert.equal(nextAppointment([], now), undefined);
  });

  it("the report's anchor is STRICTLY in the past", () => {
    // An appointment later today is not something the report can compare
    // against — using it would produce a "since last visit" block covering a
    // visit that has not happened.
    const list = [appointment("later-today", "2026-03-01T18:00:00Z"), appointment("last-week", "2026-02-22T10:00:00Z")];
    assert.equal(lastVisit(list, now)?.id, "last-week");
  });

  it("no past appointment means no anchor, which is the report's `first` state", () => {
    assert.equal(lastVisit([appointment("future", "2026-06-01T10:00:00Z")], now), undefined);
  });

  it("COMPARISON PAIRS OLDEST WITH NEWEST, not the two most recent", () => {
    // Day 3 against Day 30 is the entire point of §4.11. Pairing the newest two
    // would make the feature least useful for whoever took the most photos.
    const list = [photo("mid", "2026-02-01T10:00:00Z"), photo("new", "2026-03-01T10:00:00Z"), photo("old", "2026-01-01T10:00:00Z")];
    const pair = comparePair(list);
    assert.equal(pair?.first.id, "old");
    assert.equal(pair?.last.id, "new");
  });

  it("fewer than two photos yields no pair, which is the `insufficient` state", () => {
    assert.equal(comparePair([photo("only", "2026-01-01T10:00:00Z")]), undefined);
    assert.equal(comparePair([]), undefined);
  });

  it("does not mutate the array it is given", () => {
    const list = [photo("b", "2026-02-01T10:00:00Z"), photo("a", "2026-01-01T10:00:00Z")];
    comparePair(list);
    assert.equal(list[0].id, "b");
  });
});
