import type { OnboardingState } from "../state/OnboardingContext.tsx";
import type {
  Appointment,
  Medication,
  Milestone,
  PhotoEntry,
  RecoveryJourney,
  TimelineEntry,
  WeeklyReflection,
} from "../types/recovery.ts";

import { APPOINTMENTS, JOURNEY, MEDICATIONS, MILESTONES, PHOTOS, REFLECTIONS, TIMELINE } from "./mockJourney.ts";

export type RecoverySeed = {
  journey: RecoveryJourney;
  timeline: TimelineEntry[];
  medications: Medication[];
  appointments: Appointment[];
  photos: PhotoEntry[];
  milestones: Milestone[];
  reflections: WeeklyReflection[];
};

export const DEMO_RECOVERY_SEED: RecoverySeed = {
  journey: JOURNEY,
  timeline: TIMELINE,
  medications: MEDICATIONS,
  appointments: APPOINTMENTS,
  photos: PHOTOS,
  milestones: MILESTONES,
  reflections: REFLECTIONS,
};

const DAY_MS = 86_400_000;

function fallbackStartDate(timing?: string): string {
  const lower = timing?.toLowerCase() ?? "";
  let daysAgo = 0;
  if (lower.includes("3-7")) daysAgo = 5;
  else if (lower.includes("1-3 weeks")) daysAgo = 14;
  else if (lower.includes("1-3 months")) daysAgo = 45;
  else if (lower.includes("more than 3 months")) daysAgo = 100;
  else if (lower.includes("surgery")) daysAgo = 14;
  return new Date(Date.now() - daysAgo * DAY_MS).toISOString();
}

function bodyPartFrom(injuryType?: string): string | undefined {
  const lower = injuryType?.toLowerCase() ?? "";
  if (lower.includes("ankle")) return "Ankle";
  if (lower.includes("knee")) return "Knee";
  if (lower.includes("shoulder")) return "Shoulder";
  return undefined;
}

function labelFor(condition: string, bodyPart?: string): string {
  if (bodyPart) return `${bodyPart} recovery`;
  if (condition === "Recovery") return "My recovery";
  return condition;
}

function detailFrom(answers: OnboardingState): string {
  const details = [
    answers.injuryTiming ? `Timing: ${answers.injuryTiming}` : undefined,
    answers.walkingAbility ? `Walking: ${answers.walkingAbility}` : undefined,
    answers.pain !== undefined ? `Starting pain: ${answers.pain}/10` : undefined,
    answers.symptoms.length ? `Symptoms: ${answers.symptoms.join(", ")}` : undefined,
    answers.goal ? `Goal: ${answers.goal}` : undefined,
  ].filter(Boolean);

  return details.join(" | ");
}

export function recoverySeedFromOnboarding(answers: OnboardingState, now = new Date()): RecoverySeed {
  const condition = answers.injuryType?.trim() || "Recovery";
  const bodyPart = bodyPartFrom(condition);
  const startDate = answers.injuryDate || fallbackStartDate(answers.injuryTiming);
  const journey: RecoveryJourney = {
    id: "journey-1",
    type: condition.toLowerCase().includes("surgery") ? "surgery" : "injury",
    condition,
    bodyPart,
    label: labelFor(condition, bodyPart),
    startDate,
    goal: answers.goal,
    isActive: true,
  };

  return {
    journey,
    timeline: [
      {
        id: "entry-1",
        journeyId: journey.id,
        type: "milestone",
        date: now.toISOString(),
        title: "Recovery started",
        detail: detailFrom(answers) || condition,
        isAutoGenerated: true,
      },
    ],
    medications: [],
    appointments: [],
    photos: [],
    milestones: [],
    reflections: [],
  };
}
